language: c

os:
  - linux
  - osx

compiler:
  - gcc

osx_image: xcode11.3

addons:
  apt:
    packages:
    - nkf
  homebrew:
    packages:
    - nkf
    - gcc@9

before_script:
   - sh configure

script:
  - make install
