language: c

branches:
  only:
  - develop

os:
  - linux
  - osx

compiler:
  - gcc

osx_image: xcode13.2

addons:
  apt:
    packages:
    - nkf
  homebrew:
    packages:
    - nkf
    - gcc@9

before_script:
   - sh configure

script:
  - make install
